import { SignOutButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import { api } from "~/utils/api";

export default function Home() {
  const menuItems = api.menu.getAllMenuItems.useQuery();

  const user = useUser();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          {user.isSignedIn && <SignOutButton />}
          <h3 className="text-3xl font-bold underline">Hello world!</h3>
        </div>
      </main>
    </>
  );
}
